export const TABS = [
  { id: "json",      icon: "{}",   label: "JSON",        sub: "Formatter · Validator" },
  { id: "yaml",      icon: "≋",    label: "YAML",        sub: "JSON · YAML · Python" },
  { id: "base64",    icon: "⇄",    label: "Base64",      sub: "Encode · Decode" },
  { id: "jwt",       icon: "jwt",  label: "JWT",         sub: "Decoder · Inspector" },
  { id: "hash",      icon: "#",    label: "Hash",        sub: "MD5 · SHA-1/256/512" },
  { id: "regex",     icon: "rx",   label: "Regex",       sub: "Test · Replace" },
  { id: "color",     icon: "◉",    label: "Color",       sub: "Picker · Converter" },
  { id: "time",      icon: "⏱",   label: "Timestamp",   sub: "Converter" },
  { id: "uuid",      icon: "uid",  label: "UUID",        sub: "Generator" },
  { id: "string",    icon: "Aa",   label: "String",      sub: "Utils · Cases" },
  { id: "number",    icon: "42",   label: "Number",      sub: "Base · RNG · Round" },
  { id: "diff",      icon: "Δ",    label: "Diff",        sub: "Line · Char" },
  { id: "markdown",  icon: "md",   label: "Markdown",    sub: "Preview · Render" },
  { id: "lorem",     icon: "¶",    label: "Lorem",       sub: "Paragraphs · Words" },
  { id: "commit",    icon: "git",  label: "Commit",      sub: "Message Builder" },
  { id: "gitignore", icon: ".gi",  label: "Gitignore",   sub: "Generator · Editor" },
  { id: "password",  icon: "***",  label: "Password",    sub: "Generator · Entropy" },
  { id: "totp",      icon: "otp",  label: "TOTP",        sub: "2FA Code Generator" },
  { id: "cron",      icon: "⏰",   label: "Cron",        sub: "Parser · Next Runs" },
  { id: "http",      icon: "http", label: "HTTP Status", sub: "Codes · Reference" },
  { id: "semver",    icon: "v#",   label: "Semver",      sub: "Parse · Bump · Compare" },
  { id: "sql",       icon: "sql",  label: "SQL",         sub: "Formatter" },
  { id: "ip",        icon: "ip",   label: "IP / CIDR",   sub: "Parse · Subnet · Info" },
  { id: "qr",        icon: "qr",   label: "QR Code",     sub: "Generator · Download" },
];

export const GROUPS = [
  { label: "Data",     ids: ["json", "yaml", "base64", "jwt", "hash"] },
  { label: "Text",     ids: ["regex", "diff", "string", "markdown", "lorem"] },
  { label: "Dev",      ids: ["uuid", "commit", "color", "gitignore", "cron", "http", "semver", "sql"] },
  { label: "Security", ids: ["password", "totp"] },
  { label: "Network",  ids: ["ip", "qr"] },
  { label: "Numeric",  ids: ["time", "number"] },
];
