export const TABS = [
  { id: "json",      icon: "{}",   label: "JSON",           sub: "Formatter · Validator"    },
  { id: "yaml",      icon: "≋",    label: "YAML",           sub: "JSON · YAML · Python"     },
  { id: "base64",    icon: "⇄",    label: "Base64",         sub: "Encode · Decode · Image"  },
  { id: "jwt",       icon: "jwt",  label: "JWT",            sub: "Decode · Sign · Generate" },
  { id: "hash",      icon: "#",    label: "Hash",           sub: "MD5 · SHA-1/256/512"      },
  { id: "regex",     icon: "rx",   label: "Regex",          sub: "Test · Replace"           },
  { id: "color",     icon: "◉",    label: "Color",          sub: "Picker · Converter"       },
  { id: "palette",   icon: "🎨",   label: "Color Palette",  sub: "Shades · Harmonies · CSS" },
  { id: "time",      icon: "⏱",   label: "Timestamp",      sub: "Converter"                },
  { id: "uuid",      icon: "uid",  label: "UUID",           sub: "Generator"                },
  { id: "string",    icon: "Aa",   label: "String",         sub: "Cases · Stats · Clean"    },
  { id: "number",    icon: "42",   label: "Number",         sub: "Base · RNG · Round"       },
  { id: "ieee754",   icon: "±∞",   label: "IEEE 754",       sub: "Float Visualizer"         },
  { id: "diff",      icon: "Δ",    label: "Diff",           sub: "Line · Char"              },
  { id: "markdown",  icon: "md",   label: "Markdown",       sub: "Preview · HTML Output"    },
  { id: "lorem",     icon: "¶",    label: "Lorem",          sub: "Paragraphs · Words"       },
  { id: "commit",    icon: "git",  label: "Commit",         sub: "Message Builder"          },
  { id: "gitignore", icon: ".gi",  label: "Gitignore",      sub: "Generator · Editor"       },
  { id: "password",  icon: "***",  label: "Password",       sub: "Generator · Entropy"      },
  { id: "totp",      icon: "otp",  label: "TOTP",           sub: "2FA Code Generator"       },
  { id: "http-req",  icon: "▶",    label: "HTTP Request",   sub: "Builder · REST · curl"    },
  { id: "cron",      icon: "⏰",   label: "Cron",           sub: "Parser · Next Runs"       },
  { id: "http",      icon: "http", label: "HTTP Status",    sub: "Codes · Reference"        },
  { id: "semver",    icon: "v#",   label: "Semver",         sub: "Parse · Bump · Compare"   },
  { id: "sql",       icon: "sql",  label: "SQL",            sub: "Formatter"                },
  { id: "chmod",     icon: "rwx",  label: "Chmod",          sub: "Permission Calculator"    },
  { id: "url",       icon: "url",  label: "URL",            sub: "Parse · Build · Encode"   },
  { id: "ip",        icon: "ip",   label: "IP / CIDR",      sub: "Parse · Subnet · Info"    },
  { id: "proto",    icon: "pb",   label: "Proto Gen",      sub: "Class → .proto message"   },
  { id: "qr",        icon: "qr",   label: "QR Code",        sub: "Generator · Download"     },
];

export const GROUPS = [
  { label: "Data",     ids: ["json", "yaml", "base64", "jwt", "hash"]                                    },
  { label: "Text",     ids: ["regex", "diff", "string", "markdown", "lorem"]                             },
  { label: "Dev",      ids: ["uuid", "commit", "color", "palette", "gitignore", "cron", "http", "semver", "sql", "proto"] },
  { label: "Security", ids: ["password", "totp"]                                                          },
  { label: "Network",  ids: ["http-req", "url", "ip", "qr"]                                              },
  { label: "System",   ids: ["chmod"]                                                                     },
  { label: "Numeric",  ids: ["time", "number", "ieee754"]                                                 },
];
